/**
 * Handler Context Management
 *
 * This module provides a clean way to initialize the shared handlers with
 * network-specific configuration and SubQuery-generated entities.
 *
 * Usage in each network's index.ts:
 *
 * ```typescript
 * import { initializeHandlers } from '@oz-indexers/stellar-handlers';
 * import { AccessControlEvent, RoleMembership, ContractOwnership, Contract } from './types';
 *
 * initializeHandlers({
 *   networkId: 'stellar-mainnet',
 *   entities: { AccessControlEvent, RoleMembership, ContractOwnership, Contract },
 *   store,  // SubQuery provides this global
 * });
 *
 * export { handleRoleGranted, ... } from '@oz-indexers/stellar-handlers';
 * ```
 */

import type {
  HandlerContext,
  AccessControlEventEntity,
  RoleMembershipEntity,
  ContractOwnershipEntity,
  ContractEntity,
  Store,
} from './types';
import { ensurePolyfills } from './polyfills';

// The global context, initialized by each network
let context: HandlerContext | null = null;

/**
 * Configuration for initializing the handlers
 */
export interface InitConfig {
  /** Network identifier (e.g., 'stellar-mainnet') */
  networkId: string;
  /** Entity classes generated by SubQuery codegen */
  entities: {
    AccessControlEvent: AccessControlEventEntity;
    RoleMembership: RoleMembershipEntity;
    ContractOwnership: ContractOwnershipEntity;
    Contract: ContractEntity;
  };
  /** SubQuery store (provided as global by SubQuery runtime) */
  store: Store;
}

/**
 * Initialize the shared handlers with network-specific configuration.
 * Must be called before any handlers are invoked.
 *
 * This also ensures polyfills (TextEncoder/TextDecoder) are loaded
 * before any Stellar SDK calls.
 *
 * @param config - Network configuration and entities
 */
export function initializeHandlers(config: InitConfig): void {
  // Ensure polyfills are loaded before any handler runs
  ensurePolyfills();

  context = {
    networkId: config.networkId,
    entities: config.entities,
    store: config.store,
  };
}

/**
 * Get the current handler context.
 * Throws if handlers haven't been initialized.
 */
export function getContext(): HandlerContext {
  if (!context) {
    throw new Error(
      'Handlers not initialized. Call initializeHandlers() before using handlers.'
    );
  }
  return context;
}

/**
 * Get the network ID for the current context.
 */
export function getNetworkId(): string {
  return getContext().networkId;
}

/**
 * Get the entity classes for the current context.
 */
export function getEntities(): HandlerContext['entities'] {
  return getContext().entities;
}

/**
 * Get the store for the current context.
 */
export function getStore(): Store {
  return getContext().store;
}
