/**
 * Type definitions for SubQuery entities and store
 *
 * These interfaces define the shape of the entities generated by SubQuery codegen.
 * Each network project generates its own types from schema.graphql, but they all
 * conform to these interfaces.
 */

import { EventType, ContractType } from '@oz-indexers/common';

// Entity data interfaces (for create)
export interface AccessControlEventData {
  id: string;
  network: string;
  contract: string;
  eventType: EventType;
  blockNumber: bigint;
  timestamp: Date;
  txHash: string;
  role?: string;
  account?: string;
  sender?: string;
  previousAdminRole?: string;
  newAdminRole?: string;
  previousOwner?: string;
  newOwner?: string;
}

export interface RoleMembershipData {
  id: string;
  network: string;
  contract: string;
  role: string;
  account: string;
  grantedAt: Date;
  grantedBy?: string;
  txHash: string;
}

export interface ContractOwnershipData {
  id: string;
  network: string;
  contract: string;
  owner: string;
  previousOwner?: string;
  pendingOwner?: string;
  transferredAt: Date;
  txHash: string;
}

export interface ContractData {
  id: string;
  network: string;
  address: string;
  type: ContractType;
  firstSeenAt: Date;
  lastActivityAt: Date;
  deployTxHash?: string;
}

// Entity instance interfaces (with save method)
export interface AccessControlEventInstance extends AccessControlEventData {
  save(): Promise<void>;
}

export interface RoleMembershipInstance extends RoleMembershipData {
  save(): Promise<void>;
}

export interface ContractOwnershipInstance extends ContractOwnershipData {
  owner: string;
  previousOwner?: string;
  pendingOwner?: string;
  transferredAt: Date;
  txHash: string;
  save(): Promise<void>;
}

export interface ContractInstance extends ContractData {
  type: ContractType;
  lastActivityAt: Date;
  save(): Promise<void>;
}

// Entity class interfaces (static methods)
export interface AccessControlEventEntity {
  create(data: AccessControlEventData): AccessControlEventInstance;
}

export interface RoleMembershipEntity {
  create(data: RoleMembershipData): RoleMembershipInstance;
  get(id: string): Promise<RoleMembershipInstance | undefined>;
}

export interface ContractOwnershipEntity {
  create(data: ContractOwnershipData): ContractOwnershipInstance;
  get(id: string): Promise<ContractOwnershipInstance | undefined>;
}

export interface ContractEntity {
  create(data: ContractData): ContractInstance;
  get(id: string): Promise<ContractInstance | undefined>;
}

// Store interface
export interface Store {
  remove(entity: string, id: string): Promise<void>;
}

// Handler context - everything handlers need
export interface HandlerContext {
  networkId: string;
  entities: {
    AccessControlEvent: AccessControlEventEntity;
    RoleMembership: RoleMembershipEntity;
    ContractOwnership: ContractOwnershipEntity;
    Contract: ContractEntity;
  };
  store: Store;
}
